version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    links:
      - db
    env_file:
      - ./.envs/.local/.web
      - ./.envs/.local/.postgres

  db:
    image: postgres:14.3
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}
